# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37bea509c835396872fbce03eca8d9bdf7a60505935316f37d5af6e6916da8b4a668beeac659e4358271dd42ca9fc20b206f035ae775a1fdc2509cd297f52bca

test:
  secret_key_base: 667aa75594ee1da12015c42cd6d6642cadf58ec0ff825f58e7791079842d430b0723f8ae4e6fdd32c24934cb9c0a998aba290af1cdd17c99063fcd2f35fdb61f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
